version: '3.7'

services:
  ms_server_back:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  ms_server_db:
    image: postgres:16.3
    volumes:
      - ms_server_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_pass
      - POSTGRES_DB=django_movie_dev

volumes:
  ms_server_postgres_data: