# Generated by Django 5.1 on 2024-08-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprof',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='userprof',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/avatar/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='first_login',
            field=models.DateTimeField(null=True, verbose_name='Первый вход'),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='phone',
            field=models.CharField(blank=True, max_length=14, verbose_name='Телефон'),
        ),
    ]
