# Generated by Django 5.1 on 2024-08-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprof_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprof',
            name='birthday',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=100, null=True, verbose_name='Пол'),
        ),
    ]
