# Generated by Django 5.1.1 on 2024-09-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprof_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprof',
            name='work_phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Рабочий телефон'),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Первый вход'),
        ),
    ]
